{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "private_outputs": true,
      "provenance": [],
      "include_colab_link": true
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "view-in-github",
        "colab_type": "text"
      },
      "source": [
        "<a href=\"https://colab.research.google.com/github/jcamejo55/SyS2025/blob/main/Taller2_Dashboard_Jhon_Camejo_py.py\" target=\"_parent\"><img src=\"https://colab.research.google.com/assets/colab-badge.svg\" alt=\"Open In Colab\"/></a>"
      ]
    },
    {
      "cell_type": "markdown",
      "source": [
        "# **Dashboard**\n",
        "\n",
        "---\n",
        "\n"
      ],
      "metadata": {
        "id": "UDGjlsDvijOR"
      }
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {
        "id": "3VXAYNb3iM9Z"
      },
      "outputs": [],
      "source": [
        "#instalación de librerías\n",
        "!pip install streamlit -q"
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "pip install streamlit yt-dlp soundfile numpy pandas scikit-learn matplotlib joblib"
      ],
      "metadata": {
        "id": "CIn2NEpuBv5q"
      },
      "execution_count": null,
      "outputs": []
    },
    {
      "cell_type": "markdown",
      "source": [
        "Creación de carpeta para trabajar Multiapp en Streamlit"
      ],
      "metadata": {
        "id": "n0qGgRVyB7Ze"
      }
    },
    {
      "cell_type": "code",
      "source": [
        "!mkdir pages"
      ],
      "metadata": {
        "id": "PBEWLtuICEwq"
      },
      "execution_count": null,
      "outputs": []
    },
    {
      "cell_type": "markdown",
      "source": [
        "Página principal"
      ],
      "metadata": {
        "id": "U9dcK1JdDM_m"
      }
    },
    {
      "cell_type": "code",
      "source": [
        "%%writefile 0_👋_Bienvenida.py\n",
        "\n",
        "import streamlit as st\n",
        "\n",
        "# Configuración inicial de la página\n",
        "st.set_page_config(\n",
        "    page_title=\"Fourier Transform SyS\",\n",
        "    page_icon=\"✋\",\n",
        ")\n",
        "\n",
        "# Título principal en la interfaz\n",
        "st.write(\"# Exploración de la Transformada de Fourier 👋\")\n",
        "\n",
        "# Mensaje en la barra lateral\n",
        "st.sidebar.success(\"Elige un tema del menú lateral para comenzar.\")\n",
        "\n",
        "# Explicación introductoria y objetivos\n",
        "st.markdown(\n",
        "    \"\"\"\n",
        "    ### Propósito general:\n",
        "    * Desarrollar visualizaciones y simulaciones para representar señales en el **dominio del tiempo** y el **dominio de la frecuencia**.\n",
        "\n",
        "    ### Usos prácticos:\n",
        "    - Análisis visual del espectro de distintas señales.\n",
        "    - Representación de modulación AM y estudio de su comportamiento espectral.\n",
        "    - Evaluación de la calidad de energía mediante el cálculo del THD.\n",
        "    - Clasificación automática del género de una canción usando un modelo previamente entrenado.\n",
        "    - Gráficas dinámicas creadas con **Streamlit** para explicar los conceptos esenciales.\n",
        "\"\"\"\n",
        ")"
      ],
      "metadata": {
        "id": "Q8LbgeWYDRCX"
      },
      "execution_count": null,
      "outputs": []
    },
    {
      "cell_type": "markdown",
      "source": [
        "Páginas\n",
        "\n",
        "La página se debe enviar al directorio \\pages."
      ],
      "metadata": {
        "id": "ANNf42FKElDF"
      }
    },
    {
      "cell_type": "markdown",
      "source": [
        "## ***1. Cuarto punto: Modulación AM***\n",
        "\n",
        "---\n",
        "\n"
      ],
      "metadata": {
        "id": "3AeiYvPnE77O"
      }
    },
    {
      "cell_type": "code",
      "source": [
        "%%writefile 1_Mod_AM_🔉.py\n",
        "import streamlit as st\n",
        "import numpy as np\n",
        "from scipy import signal\n",
        "from scipy.io import wavfile\n",
        "import matplotlib.pyplot as plt\n",
        "import yt_dlp\n",
        "import os\n",
        "\n",
        "# --- Funciones de procesamiento ---\n",
        "\n",
        "def obtener_audio_desde_youtube(url, inicio=20, fin=25, nueva_fs=22050):\n",
        "    \"\"\"\n",
        "    Descarga el audio desde una URL de YouTube, selecciona un segmento específico,\n",
        "    convierte a mono, ajusta la frecuencia de muestreo y devuelve un arreglo NumPy.\n",
        "    \"\"\"\n",
        "    archivo_temp = \"temp_audio\"\n",
        "    opciones_descarga = {\n",
        "        'format': 'bestaudio/best',\n",
        "        'postprocessors': [{\n",
        "            'key': 'FFmpegExtractAudio',\n",
        "            'preferredcodec': 'wav',\n",
        "            'preferredquality': '192',\n",
        "        }],\n",
        "        'outtmpl': archivo_temp,\n",
        "        'quiet': True,\n",
        "    }\n",
        "\n",
        "    try:\n",
        "        with yt_dlp.YoutubeDL(opciones_descarga) as ydl:\n",
        "            ydl.download([url])\n",
        "\n",
        "        fs, datos_audio = wavfile.read(archivo_temp + \".wav\")\n",
        "\n",
        "        st.info(f\"Extrayendo audio entre los segundos {inicio} y {fin}.\")\n",
        "        i_inicio = int(inicio * fs)\n",
        "        i_fin = int(fin * fs)\n",
        "\n",
        "        if i_fin > len(datos_audio):\n",
        "            st.warning(f\"La duración del audio es menor a {fin}s. Se tomará el máximo disponible.\")\n",
        "            i_fin = len(datos_audio)\n",
        "\n",
        "        if i_inicio >= len(datos_audio):\n",
        "            st.error(f\"El segundo {inicio}s excede la duración del audio. Proceso cancelado.\")\n",
        "            os.remove(archivo_temp + \".wav\")\n",
        "            return None, None\n",
        "\n",
        "        datos_audio = datos_audio[i_inicio:i_fin]\n",
        "\n",
        "        if datos_audio.ndim > 1:\n",
        "            datos_audio = np.mean(datos_audio, axis=1)\n",
        "\n",
        "        if fs != nueva_fs:\n",
        "            total_muestras = int(len(datos_audio) * float(nueva_fs) / fs)\n",
        "            datos_audio = signal.resample(datos_audio, total_muestras)\n",
        "            fs = nueva_fs\n",
        "\n",
        "        if np.max(np.abs(datos_audio)) > 0:\n",
        "            datos_audio = datos_audio / np.max(np.abs(datos_audio))\n",
        "\n",
        "        os.remove(archivo_temp + \".wav\")\n",
        "\n",
        "        return datos_audio, fs\n",
        "\n",
        "    except Exception as e:\n",
        "        st.error(f\"Ocurrió un error durante el procesamiento: {e}\")\n",
        "        return None, None\n",
        "\n",
        "# --- Configuración de la interfaz ---\n",
        "\n",
        "st.set_page_config(layout=\"wide\")\n",
        "st.title(\"📻 Demostración de Modulación AM\")\n",
        "\n",
        "st.markdown(\"\"\"\n",
        "Explora aquí cómo se realiza una **modulación y demodulación de amplitud** usando una señal de audio\n",
        "extraída de YouTube. Se aplicará un detector coherente para recuperar la señal original.\n",
        "\"\"\")\n",
        "\n",
        "st.markdown(\"\"\"\n",
        "La **modulación AM** consiste en modificar la amplitud de una onda portadora sinusoidal según una señal de mensaje.\n",
        "A continuación, se utilizará una señal de audio como mensaje, se aplicará modulación AM y se demostrará cómo se recupera.\n",
        "\"\"\")\n",
        "\n",
        "# --- Parámetros personalizables ---\n",
        "st.sidebar.header(\"Configuración del Proceso\")\n",
        "url = st.sidebar.text_input(\"URL de YouTube:\", \"https://www.youtube.com/watch?v=dQw4w9WgXcQ\")\n",
        "Am = st.sidebar.slider(\"Amplitud de Portadora (Ac)\", 0.1, 5.0, 1.0, 0.1)\n",
        "fc = st.sidebar.slider(\"Frecuencia de Portadora (fc) en Hz\", 500, 5000, 5000, 100)\n",
        "k_am = st.sidebar.slider(\"Índice de Modulación (ka)\", 0.1, 1.5, 1.0, 0.1)\n",
        "\n",
        "if st.sidebar.button(\"Iniciar Modulación\"):\n",
        "    if not url:\n",
        "        st.warning(\"Por favor, escribe una URL válida.\")\n",
        "    else:\n",
        "        with st.spinner(\"Procesando audio...\"):\n",
        "            señal, fs = obtener_audio_desde_youtube(url)\n",
        "\n",
        "        if señal is not None:\n",
        "            dur = len(señal) / fs\n",
        "            t = np.linspace(0, dur, len(señal), endpoint=False)\n",
        "\n",
        "            # --- Visualizar señal original ---\n",
        "            st.header(\"1. Señal de Audio Original\")\n",
        "            fig1, ax1 = plt.subplots(figsize=(12, 4))\n",
        "            ax1.plot(t, señal, color='steelblue')\n",
        "            ax1.set_title(\"Audio Inicial\")\n",
        "            ax1.set_xlabel(\"Tiempo [s]\")\n",
        "            ax1.set_ylabel(\"Amplitud Normalizada\")\n",
        "            ax1.grid()\n",
        "            st.pyplot(fig1)\n",
        "            st.audio(señal, sample_rate=fs)\n",
        "\n",
        "            # --- Modulación AM ---\n",
        "            st.header(\"2. Señal Modulada en AM\")\n",
        "            st.markdown(\"Se utiliza la fórmula: $s(t) = A_c [1 + k_a m(t)] \\\\cos(2\\\\pi f_c t)$\")\n",
        "\n",
        "            with st.expander(\"¿Cómo se ve el espectro en AM?\"):\n",
        "                st.markdown(r\"\"\"\n",
        "                La modulación genera un espectro compuesto por:\n",
        "                - La portadora en $\\\\pm f_c$\n",
        "                - Dos bandas laterales: $M(f \\\\pm f_c)$\n",
        "                Resultado de:\n",
        "                $$ Y(f) = \\frac{A_c}{2}[\\delta(f - f_c) + \\delta(f + f_c)] + \\frac{1}{2}[M(f - f_c) + M(f + f_c)] $$\n",
        "                \"\"\")\n",
        "\n",
        "            portadora = Am * np.cos(2 * np.pi * fc * t)\n",
        "            señal_am = (1 + k_am * señal) * portadora\n",
        "\n",
        "            fig2, ax2 = plt.subplots(figsize=(12, 4))\n",
        "            ax2.plot(t, señal_am, color='crimson')\n",
        "            ax2.set_title(\"Señal Modulada (AM)\")\n",
        "            ax2.set_xlabel(\"Tiempo [s]\")\n",
        "            ax2.set_ylabel(\"Amplitud\")\n",
        "            ax2.grid()\n",
        "            st.pyplot(fig2)\n",
        "            st.audio(señal_am, sample_rate=fs)\n",
        "\n",
        "            # --- Demodulación coherente ---\n",
        "            st.header(\"3. Demodulación Paso a Paso\")\n",
        "\n",
        "            # Paso 1: Multiplicación\n",
        "            st.subheader(\"Paso 1: Multiplicación por la Portadora\")\n",
        "            producto = señal_am * portadora\n",
        "            fig3, ax3 = plt.subplots(figsize=(12, 4))\n",
        "            ax3.plot(t, producto, color='orange')\n",
        "            ax3.set_title(\"Después de multiplicar por la portadora\")\n",
        "            ax3.set_xlabel(\"Tiempo [s]\")\n",
        "            ax3.set_ylabel(\"Amplitud\")\n",
        "            ax3.grid()\n",
        "            st.pyplot(fig3)\n",
        "            st.audio(producto, sample_rate=fs)\n",
        "            st.warning(\"El audio aquí contiene componentes no deseadas de alta frecuencia.\")\n",
        "\n",
        "            # Paso 2: Filtro pasa bajas\n",
        "            st.subheader(\"Paso 2: Aplicación de Filtro Pasa-Bajas\")\n",
        "            fcorte = 4000\n",
        "            orden = 4\n",
        "            wn = 2 * fcorte / fs\n",
        "            b, a = signal.butter(orden, wn, btype='low')\n",
        "            señal_filtrada = signal.lfilter(b, a, producto)\n",
        "            fig4, ax4 = plt.subplots(figsize=(12, 4))\n",
        "            ax4.plot(t, señal_filtrada, color='forestgreen')\n",
        "            ax4.set_title(\"Después del filtrado pasa-bajas\")\n",
        "            ax4.set_xlabel(\"Tiempo [s]\")\n",
        "            ax4.set_ylabel(\"Amplitud\")\n",
        "            ax4.grid()\n",
        "            st.pyplot(fig4)\n",
        "            st.audio(señal_filtrada, sample_rate=fs)\n",
        "            st.info(\"El filtrado ha limpiado el contenido indeseado de alta frecuencia.\")\n",
        "\n",
        "            # Paso 3: Restauración por ganancia\n",
        "            st.subheader(\"Paso 3: Ajuste Final de Ganancia\")\n",
        "            ganancia = 2 / (Am ** 2)\n",
        "            señal_recuperada = señal_filtrada * ganancia\n",
        "            fig5, ax5 = plt.subplots(figsize=(12, 4))\n",
        "            ax5.plot(t, señal_recuperada, label=\"Recuperada\", color='royalblue')\n",
        "            ax5.plot(t, señal, label=\"Original\", linestyle='--', color='red', alpha=0.7)\n",
        "            ax5.set_title(\"Comparación entre Señal Recuperada y Original\")\n",
        "            ax5.set_xlabel(\"Tiempo [s]\")\n",
        "            ax5.set_ylabel(\"Amplitud\")\n",
        "            ax5.legend()\n",
        "            ax5.grid()\n",
        "            st.pyplot(fig5)\n",
        "            st.audio(señal_recuperada, sample_rate=fs)\n",
        "            st.success(\"¡Proceso finalizado! La señal ha sido demodulada exitosamente.\")"
      ],
      "metadata": {
        "id": "UFUIzOnHFcFR"
      },
      "execution_count": null,
      "outputs": []
    },
    {
      "cell_type": "code",
      "source": [
        "!mv 1_Modulación_AM_🔉.py pages/"
      ],
      "metadata": {
        "id": "MyO6S_dBF3oN"
      },
      "execution_count": null,
      "outputs": []
    },
    {
      "cell_type": "markdown",
      "source": [
        "## ***2. Quinto punto: Aplicación en circuitos eléctricos-potencia (THD)***\n",
        "\n",
        "---\n",
        "\n"
      ],
      "metadata": {
        "id": "KekuuvlfGGR1"
      }
    },
    {
      "cell_type": "code",
      "source": [
        "%%writefile 2_Factor_de_Potencia_THD_⚡.py\n",
        "import streamlit as st\n",
        "import numpy as np\n",
        "import matplotlib.pyplot as plt\n",
        "from scipy.fft import fft, fftfreq\n",
        "import scipy.integrate as integrate\n",
        "\n",
        "st.set_page_config(\n",
        "    page_title=\"Factor de Potencia (THD)\",\n",
        "    page_icon=\"⚡\",\n",
        "    layout=\"wide\",\n",
        ")\n",
        "\n",
        "st.markdown(\"\"\"\n",
        "    # Factor de Potencia y Distorsión Armónica Total (THD) ⚡\n",
        "\n",
        "    ### ¿Qué es la Distorsión Armónica Total (THD) y el Factor de Potencia?\n",
        "\n",
        "    En un circuito eléctrico, la forma de onda de la corriente o el voltaje puede no ser una sinusoide pura,\n",
        "    especialmente cuando hay cargas no lineales (como rectificadores, variadores de velocidad, etc.).\n",
        "    Esta desviación de la forma de onda ideal se debe a la presencia de **armónicos**, que son componentes\n",
        "    sinusoidales a múltiplos enteros de la frecuencia fundamental.\n",
        "\n",
        "    *   **Distorsión Armónica Total (THD):** Es una medida de cuánta distorsión armónica hay en una señal. Se define como la relación entre la suma cuadrática (RMS) de todas las componentes armónicas y la componente fundamental. Para la corriente ($I$) y el voltaje ($V$):\n",
        "\n",
        "    $$THD_I= (\\sqrt{I_2 ^2 + I_3 ^2 + I_4 ^2 +\\dots})/({I_1}) * 100\\%$$\n",
        "\n",
        "    $$THD_V=(\\sqrt{V_2 ^2 + V_3 ^2 + V_4 ^2 + \\dots})/({V_1}) * 100\\%$$\n",
        "\n",
        "    Donde $I_n$ y $V_n$ son los valores RMS de la n-ésima componente armónica de la corriente y el voltaje, respectivamente, y $I_1$ y $V_1$ son los valores RMS de la fundamental.\n",
        "\n",
        "    *   **Factor de Potencia (FP):** En circuitos de corriente alterna, el factor de potencia es la relación entre\n",
        "        la potencia activa (real) utilizada por la carga y la potencia aparente total suministrada. Se puede\n",
        "        descomponer en dos partes:\n",
        "\n",
        "        $$ FP = FP_{desplazamiento} * FP_{distorsión} $$\n",
        "\n",
        "        -   **Factor de Potencia por Desplazamiento ($\\cos(\\phi)$):** Relacionado con el ángulo de fase ($\\phi$) entre\n",
        "            la componente fundamental del voltaje y la fundamental de la corriente.\n",
        "        -   **Factor de Potencia por Distorsión:** Relacionado con la presencia de armónicos.\n",
        "\n",
        "        Cuando la forma de onda no es sinusoidal pura, el factor de potencia total también se ve afectado por la\n",
        "        distorsión.\n",
        "\n",
        "    ### Cálculo del THD desde la FFT\n",
        "\n",
        "    La Transformada Rápida de Fourier (FFT) nos permite descomponer una señal en sus componentes de frecuencia,\n",
        "    revelando las magnitudes de la fundamental y de los armónicos.\n",
        "\n",
        "    Dada una señal $x(t)$ muestreada en el tiempo, su FFT $X[k]$ nos da la magnitud y fase de las componentes\n",
        "    en diferentes frecuencias. La magnitud de la componente fundamental ($X[k_1]$) y de los armónicos ($X[k_n]$)\n",
        "    se encuentran en los índices $k_1$ y $k_n$ correspondientes a las frecuencias $f_1$ y $n \\cdot f_1$.\n",
        "\n",
        "    El valor RMS de una componente sinusoidal con magnitud $A$ es $A/\\sqrt{2}$. Para una señal real $x(t)$ de longitud $N$, la magnitud de la FFT $X[k]$ está relacionada con la amplitud de la componente de frecuencia $f_k$.\n",
        "\n",
        "    Para una señal real $x$ de $N$ muestras, con fundamental en la frecuencia $f_1$:\n",
        "    1.  Calcular la FFT: `X = fft(x)`\n",
        "    2.  Calcular las frecuencias correspondientes: `freqs = fftfreq(N, 1/fs)`\n",
        "    3.  Identificar el índice $k_1$ correspondiente a la frecuencia fundamental $f_1$.\n",
        "    4.  Identificar los índices $k_n$ correspondientes a los armónicos $n \\cdot f_1$.\n",
        "    5.  La magnitud de la fundamental es $|X[k_1]|$. El valor RMS de la fundamental es $I_1 = |X[k_1]| / (\\sqrt{2} \\cdot N/2) = |X[k_1]| \\cdot \\sqrt{2} / N$ para señales reales.\n",
        "    6.  Las magnitudes de los armónicos son $|X[k_n]|$. Los valores RMS de los armónicos son $I_n = |X[k_n]| \\cdot \\sqrt{2} / N$.\n",
        "    7.  Sustituir en la fórmula del THD.\n",
        "\n",
        "    Una forma práctica usando `numpy` para la magnitud del espectro unilateral ($N/2+1$ puntos):\n",
        "    Sea $P1$ el espectro de magnitud unilateral normalizado (como en el ejemplo de AM):\n",
        "    $P1[k]$ es la amplitud de la componente en frecuencia $f_k$.\n",
        "\n",
        "    El valor RMS de la fundamental es $I_1 = P1[k_1]/\\sqrt{2}$.\n",
        "\n",
        "    El valor RMS de los armónicos es $I_n = P1[k_n]/\\sqrt{2}$.\n",
        "\n",
        "    Entonces:\n",
        "\n",
        "    $$ THD_I = (\\sqrt{\\sum_{n=2}^{N_{harm}} (P1[k_n]/\\sqrt{2})^2})/(P1[k_1]/\\sqrt{2}) = (\\sqrt{\\sum_{n=2}^{N_{harm}} P1[k_n]^2})/(P1[k_1]) $$\n",
        "\n",
        "    Donde $N_{harm}$ es el número de armónicos considerados.\n",
        "\n",
        "    ### Cálculo de la Distorsión del Factor de Potencia con base al THD\n",
        "\n",
        "    El factor de potencia total en presencia de armónicos se puede calcular como:\n",
        "\n",
        "    $$ FP = P/S = (Potencia Activa)/(Potencia Aparente) $$\n",
        "\n",
        "    La potencia aparente ($S$) para formas de onda no sinusoidales se calcula usando los valores RMS totales (fundamental + armónicos) del voltaje ($V_{RMS}$) y la corriente ($I_{RMS}$):\n",
        "\n",
        "    $$ S = V_{RMS} \\cdot I_{RMS} $$\n",
        "\n",
        "    El valor RMS total de una señal con armónicos es:\n",
        "    $$ X_{RMS} = \\sqrt{X_1^2 + X_2^2 + X_3^2 + \\dots} = X_1 \\sqrt{1 + \\text{THD}_X^2} $$\n",
        "    Donde $X$ puede ser voltaje o corriente.\n",
        "\n",
        "    La potencia activa ($P$) es la potencia disipada en la resistencia y se calcula como la suma de las potencias activas de cada armónico (solo contribuye la fundamental y los armónicos presentes tanto en voltaje como en corriente y en fase):\n",
        "\n",
        "    $$ P = V_1 I_1 \\cos(\\phi_1) + V_2 I_2 \\cos(\\phi_2) + \\dots $$\n",
        "    En muchos casos (voltaje de fuente casi sinusoidal), la potencia activa es dominada por la fundamental: $P = V_1 I_1 \\cos(\\phi_1)$.\n",
        "\n",
        "    El factor de potencia por distorsión se relaciona con el THD de la corriente por la siguiente fórmula:\n",
        "\n",
        "    $$ FP_{distorsión} = (I_1)/(I_{RMS}) = (I_1)/(I_1 \\sqrt{1 + THD_I^2}) = (1)/(\\sqrt{1 + THD_I^2}) $$\n",
        "\n",
        "    Así, el factor de potencia total puede aproximarse (si el voltaje de la fuente es ideal sinusoidal y la distorsión del voltaje es despreciable) como:\n",
        "\n",
        "    $$ FP = \\cos(\\phi_1) * 1/(\\sqrt{1 + THD_I^2}) $$\n",
        "\n",
        "    Donde $\\cos(\\phi_1)$ es el factor de potencia por desplazamiento, calculado con el ángulo de fase entre la fundamental de voltaje y corriente. En circuitos puramente resistivos ($\\phi_1=0$), $\\cos(\\phi_1)=1$, y el FP se reduce a $1/(\\sqrt{1 + THD_I^2})$.\n",
        "\n",
        "    ### Ejemplo Ilustrativo: Rectificador de Onda Completa\n",
        "\n",
        "    Simularemos la corriente a través de una carga conectada a un rectificador de onda completa, alimentado por una fuente de voltaje sinusoidal. Analizaremos dos casos de carga: puramente resistiva (R) y RC en serie.\n",
        "\n",
        "    Consideramos una fuente de voltaje sinusoidal: $v(t) = V_p \\sin(2\\pi f t)$.\n",
        "    La salida del rectificador de onda completa (asumiendo diodos ideales) es $|v(t)| = V_p |\\sin(2\\pi f t)|$.\n",
        "\n",
        "    La corriente a través de la carga $i(t)$ dependerá de la impedancia de la carga a la tensión rectificada.\n",
        "\n",
        "    #### Caso i) Carga puramente Resistiva (R)\n",
        "\n",
        "    Para una carga puramente resistiva $R$, la corriente instantánea es simplemente $i(t) = |v(t)| / R = (V_p/R) |\\sin(2\\pi f t)|$. La forma de onda de la corriente es idéntica a la de la tensión rectificada, escalada por $1/R$.\n",
        "\n",
        "    #### Caso ii) Carga RC en Serie\n",
        "\n",
        "    Para una carga RC en serie, la corriente es más compleja de calcular analíticamente, ya que depende de la dinámica de carga y descarga del condensador. La corriente fluirá principalmente cuando el voltaje rectificado sea mayor que el voltaje en el condensador. El condensador tenderá a mantener un voltaje cercano al pico, y la corriente fluirá en pulsos cortos cuando la tensión de entrada supere la tensión del condensador. Esto resulta en una forma de onda de corriente muy distorsionada.\n",
        "\n",
        "    ### Simulación y Análisis\n",
        "\n",
        "    Utilizaremos las siguientes condiciones para la simulación:\n",
        "    *   Frecuencia de la fuente: $f = 60$ Hz\n",
        "    *   Voltaje pico de la fuente: $V_p = 10$ V\n",
        "    *   Frecuencia de muestreo: $fs = 200 \\cdot f$ (suficiente para capturar armónicos)\n",
        "    *   Duración de la simulación: Varios ciclos de la fundamental (ej: 4 ciclos)\n",
        "\n",
        "    Sliders de control para R y C:\n",
        "\"\"\")\n",
        "\n",
        "# --- Parámetros de simulación ---\n",
        "f = 60  # Hz\n",
        "Vp = 10 # V\n",
        "fs_sim = 200 * f # Hz\n",
        "duration_sim = 4 / f # segundos (4 ciclos)\n",
        "N_sim = int(fs_sim * duration_sim)\n",
        "t_sim = np.linspace(0, duration_sim, N_sim, endpoint=False)\n",
        "\n",
        "st.subheader(\"Parámetros de Carga\")\n",
        "resistance = st.slider(\"Valor de la Resistencia R (Ohms)\", 1.0, 100.0, 10.0, step=1.0)\n",
        "capacitance_nf = st.slider(\"Valor del Condensador C (nF)\", 0.0, 1000.0, 0.0, step=10.0)\n",
        "capacitance = capacitance_nf * 1e-9 # Convertir nF a Faradios\n",
        "\n",
        "# --- Cálculo de señales ---\n",
        "v_source = Vp * np.sin(2 * np.pi * f * t_sim)\n",
        "v_rectified = np.abs(v_source)\n",
        "\n",
        "i_r_load = v_rectified / resistance\n",
        "\n",
        "# Simulación de carga RC (simplificada por simulación numérica simple)\n",
        "# Esto es una aproximación. Una simulación de circuito real es compleja.\n",
        "# Aquí, simulamos la respuesta de un circuito RC a la tensión rectificada.\n",
        "# Ecuación: v_rectified(t) = R*i(t) + v_c(t)\n",
        "# dv_c/dt = i(t)/C\n",
        "# i(t) = (v_rectified(t) - v_c(t))/R\n",
        "# dv_c/dt = (v_rectified(t) - v_c(t))/(R*C)\n",
        "# Usamos integración numérica simple (Euler)\n",
        "dt = 1.0 / fs_sim\n",
        "i_rc_load = np.zeros(N_sim)\n",
        "v_c = 0.0\n",
        "\n",
        "if capacitance > 1e-12: # Solo si hay capacitor\n",
        "    for k in range(N_sim - 1):\n",
        "        i_rc_load[k] = (v_rectified[k] - v_c) / resistance\n",
        "        dv_c = i_rc_load[k] * dt / capacitance\n",
        "        v_c += dv_c\n",
        "        # El capacitor no puede tener un voltaje mayor al pico de la fuente rectificada\n",
        "        if v_c > v_rectified[k+1]:\n",
        "             v_c = v_rectified[k+1]\n",
        "else: # Comportamiento resistivo si C es muy pequeño\n",
        "     i_rc_load = i_r_load\n",
        "\n",
        "\n",
        "# --- Cálculo de FFT y THD ---\n",
        "\n",
        "def calculate_thd(signal, fs, fundamental_freq, num_harmonics=10):\n",
        "    \"\"\" Calcula el THD de una señal \"\"\"\n",
        "    N = len(signal)\n",
        "    yf = fft(signal)\n",
        "    xf = fftfreq(N, 1/fs)\n",
        "\n",
        "    # Encontrar la fundamental\n",
        "    # Buscar el pico cerca de la fundamental_freq (o 2*fundamental_freq para rectificada)\n",
        "    # La frecuencia fundamental de la señal rectificada de 60Hz es 120Hz\n",
        "    target_fund_freq = 2 * fundamental_freq\n",
        "    fundamental_idx = np.argmin(np.abs(xf - target_fund_freq))\n",
        "    fundamental_magnitude = 2.0/N * np.abs(yf[fundamental_idx])\n",
        "\n",
        "    if fundamental_magnitude < 1e-9: # Evitar división por cero\n",
        "        return np.nan, xf[0:N//2], 2.0/N * np.abs(yf[0:N//2]) # Retornar espectro unilateral\n",
        "\n",
        "    harmonic_magnitudes_sq = 0\n",
        "    max_harm_idx = 0\n",
        "    freqs_unilateral = xf[0:N//2]\n",
        "    magnitudes_unilateral = 2.0/N * np.abs(yf[0:N//2])\n",
        "\n",
        "    for n in range(2, num_harmonics + 2): # Armónicos de la fundamental rectificada (2*f, 3*f, 4*f, etc.)\n",
        "        harmonic_freq = n * target_fund_freq\n",
        "        harmonic_idx = np.argmin(np.abs(xf - harmonic_freq))\n",
        "        if harmonic_idx < N // 2: # Asegurarse de estar en el rango unilateral\n",
        "             harmonic_magnitude = 2.0/N * np.abs(yf[harmonic_idx])\n",
        "             harmonic_magnitudes_sq += harmonic_magnitude**2\n",
        "             max_harm_idx = max(max_harm_idx, harmonic_idx)\n",
        "\n",
        "\n",
        "    thd = np.sqrt(harmonic_magnitudes_sq) / fundamental_magnitude * 100\n",
        "\n",
        "    # Recortar espectro para visualización hasta el último armónico considerado + un poco\n",
        "    view_limit_hz = (num_harmonics + 2) * target_fund_freq * 1.2\n",
        "    view_idx_limit = np.argmin(np.abs(freqs_unilateral - view_limit_hz)) + 10\n",
        "    view_idx_limit = min(view_idx_limit, N // 2) # No exceder el límite de N//2\n",
        "\n",
        "    return thd, freqs_unilateral[:view_idx_limit], magnitudes_unilateral[:view_idx_limit]\n",
        "\n",
        "\n",
        "thd_r, freqs_r, mags_r = calculate_thd(i_r_load, fs_sim, f)\n",
        "thd_rc, freqs_rc, mags_rc = calculate_thd(i_rc_load, fs_sim, f)\n",
        "\n",
        "# Cálculo del Factor de Potencia por Distorsión\n",
        "fp_distortion_r = 1 / np.sqrt(1 + (thd_r/100)**2) if not np.isnan(thd_r) else np.nan\n",
        "fp_distortion_rc = 1 / np.sqrt(1 + (thd_rc/100)**2) if not np.isnan(thd_rc) else np.nan\n",
        "\n",
        "\n",
        "# --- Mostrar resultados ---\n",
        "st.subheader(\"Resultados de la Simulación\")\n",
        "\n",
        "col1, col2 = st.columns(2)\n",
        "\n",
        "with col1:\n",
        "    st.markdown(\"### Carga Resistiva (R)\")\n",
        "    st.write(f\"Resistencia: {resistance} Ohms\")\n",
        "    st.write(f\"THD de la Corriente: {thd_r:.2f} %\" if not np.isnan(thd_r) else \"THD no calculado\")\n",
        "    st.write(f\"Factor de Potencia por Distorsión: {fp_distortion_r:.4f}\" if not np.isnan(fp_distortion_r) else \"FP Distorsión no calculado\")\n",
        "\n",
        "\n",
        "with col2:\n",
        "    st.markdown(\"### Carga RC en Serie\")\n",
        "    st.write(f\"Resistencia: {resistance} Ohms\")\n",
        "    st.write(f\"Capacitancia: {capacitance_nf} nF\")\n",
        "    st.write(f\"THD de la Corriente: {thd_rc:.2f} %\" if not np.isnan(thd_rc) else \"THD no calculado\")\n",
        "    st.write(f\"Factor de Potencia por Distorsión: {fp_distortion_rc:.4f}\" if not np.isnan(fp_distortion_rc) else \"FP Distorsión no calculado\")\n",
        "\n",
        "# --- Graficar formas de onda ---\n",
        "st.subheader(\"Formas de Onda de Corriente\")\n",
        "fig_waveforms, ax_waveforms = plt.subplots(figsize=(12, 6))\n",
        "ax_waveforms.plot(t_sim, i_r_load, label=\"Carga Resistiva (R)\", alpha=0.7)\n",
        "if capacitance_nf > 0:\n",
        "    ax_waveforms.plot(t_sim, i_rc_load, label=f\"Carga RC (R={resistance}Ω, C={capacitance_nf}nF)\", alpha=0.7)\n",
        "ax_waveforms.set_xlabel(\"Tiempo [s]\")\n",
        "ax_waveforms.set_ylabel(\"Corriente [A]\")\n",
        "ax_waveforms.set_title(\"Corriente a través de la Carga\")\n",
        "ax_waveforms.legend()\n",
        "ax_waveforms.grid(True)\n",
        "st.pyplot(fig_waveforms)\n",
        "\n",
        "# --- Graficar espectros de frecuencia ---\n",
        "st.subheader(\"Espectros de Frecuencia de Corriente\")\n",
        "fig_spectrums, ax_spectrums = plt.subplots(figsize=(12, 6))\n",
        "ax_spectrums.plot(freqs_r, mags_r, label=\"Espectro Corriente Carga R\", alpha=0.7)\n",
        "if capacitance_nf > 0:\n",
        "    ax_spectrums.plot(freqs_rc, mags_rc, label=f\"Espectro Corriente Carga RC (R={resistance}Ω, C={capacitance_nf}nF)\", alpha=0.7)\n",
        "ax_spectrums.set_xlabel(\"Frecuencia [Hz]\")\n",
        "ax_spectrums.set_ylabel(\"Magnitud\")\n",
        "ax_spectrums.set_title(\"Espectro de Frecuencia de la Corriente\")\n",
        "ax_spectrums.set_xlim(0, 15 * f) # Limitar eje X para mejor visualización de armónicos\n",
        "ax_spectrums.legend()\n",
        "ax_spectrums.grid(True)\n",
        "st.pyplot(fig_spectrums)\n",
        "\n",
        "# --- Discusión de Resultados ---\n",
        "st.subheader(\"Discusión de Resultados\")\n",
        "st.markdown(\"\"\"\n",
        "    **Carga Puramente Resistiva (R):**\n",
        "    - La forma de onda de la corriente sigue la forma de onda de la tensión rectificada (ondas sinusoidales con los semiciclos negativos invertidos).\n",
        "    - El espectro de frecuencia muestra una componente fundamental a 120 Hz (el doble de la frecuencia de la fuente) y armónicos pares (240 Hz, 360 Hz, etc.).\n",
        "    - El THD de la corriente será significativo, ya que la forma de onda está lejos de ser una sinusoide pura.\n",
        "    - El factor de potencia por desplazamiento es 1 (corriente en fase con la tensión rectificada), pero el factor de potencia total se reduce debido a la distorsión armónica.\n",
        "\n",
        "    **Carga RC en Serie:**\n",
        "    - La adición de un condensador modifica drásticamente la forma de onda de la corriente. La corriente tiende a fluir en pulsos cortos y de alta amplitud cuando el voltaje de entrada supera el voltaje del condensador, que se carga cerca del pico.\n",
        "    - Esto resulta en una forma de onda de corriente mucho más distorsionada en comparación con la carga puramente resistiva.\n",
        "    - El espectro de frecuencia de la corriente con carga RC contendrá armónicos de mayor amplitud y posiblemente a frecuencias más altas.\n",
        "    - El THD de la corriente aumenta significativamente con la presencia del condensador.\n",
        "    - El factor de potencia por distorsión (y, por lo tanto, el factor de potencia total, asumiendo un FP por desplazamiento cercano a 1) disminuye a medida que aumenta el THD de la corriente.\n",
        "\n",
        "    **Observaciones:**\n",
        "    - Puedes experimentar con diferentes valores de R y C usando los sliders.\n",
        "    - Aumentar C tenderá a reducir la duración de los pulsos de corriente y aumentar su amplitud, incrementando el THD.\n",
        "    - Un THD de corriente alto implica un factor de potencia reducido y puede causar problemas en el sistema eléctrico (calentamiento de transformadores, sobrecargas en neutros, etc.).\n",
        "    - Esta simulación es una aproximación simplificada. Un análisis más preciso requeriría una simulación de circuito detallada considerando las características de los diodos reales y la interacción completa entre la fuente, el rectificador y la carga.\n",
        "\"\"\")"
      ],
      "metadata": {
        "id": "_JwBZzEQGcNX"
      },
      "execution_count": null,
      "outputs": []
    },
    {
      "cell_type": "code",
      "source": [
        "!mv 2_Factor_de_Potencia_THD_⚡.py pages/"
      ],
      "metadata": {
        "id": "rl6VcOIGGrct"
      },
      "execution_count": null,
      "outputs": []
    },
    {
      "cell_type": "markdown",
      "source": [
        "## ***3. Detector de género***\n",
        "\n",
        "---\n",
        "\n"
      ],
      "metadata": {
        "id": "3-VCTjvBGuRr"
      }
    },
    {
      "cell_type": "code",
      "source": [
        "%%writefile 3_Detector_de_Genero_Musical_🎶.py\n",
        "import streamlit as st\n",
        "import yt_dlp\n",
        "import os\n",
        "import soundfile as sf\n",
        "import numpy as np\n",
        "import librosa\n",
        "import joblib\n",
        "import io\n",
        "\n",
        "#--- Funciones Auxiliares ---#\n",
        "\n",
        "def download_youtube_audio(url, output_path='downloaded_audio'):\n",
        "    \"\"\"Descarga el audio de un video de YouTube en formato .wav.\"\"\"\n",
        "    if not os.path.exists(output_path):\n",
        "        os.makedirs(output_path)\n",
        "\n",
        "    ydl_opts = {\n",
        "        'format': 'bestaudio/best',\n",
        "        'postprocessors': [{\n",
        "            'key': 'FFmpegExtractAudio',\n",
        "            'preferredcodec': 'wav',\n",
        "            'preferredquality': '192',\n",
        "        }],\n",
        "        'outtmpl': os.path.join(output_path, '%(title)s.%(ext)s'),\n",
        "        'quiet': True,\n",
        "        'noplaylist': True,\n",
        "    }\n",
        "\n",
        "    try:\n",
        "        with yt_dlp.YoutubeDL(ydl_opts) as ydl:\n",
        "            info_dict = ydl.extract_info(url, download=True)\n",
        "            base_filename = ydl.prepare_filename(info_dict)\n",
        "            output_filename = os.path.splitext(base_filename)[0] + '.wav'\n",
        "            return output_filename\n",
        "    except Exception as e:\n",
        "        st.error(f\"Error al descargar de YouTube: {e}\")\n",
        "        return None\n",
        "\n",
        "def extract_features(audio_path, fixed_length):\n",
        "    \"\"\"\n",
        "    Extrae características MFCC de un archivo de audio, las aplana y las ajusta a una longitud fija.\n",
        "    \"\"\"\n",
        "    try:\n",
        "        y, sr = librosa.load(audio_path, sr=None, duration=60)\n",
        "        mfccs = librosa.feature.mfcc(y=y, sr=sr, n_mfcc=20)\n",
        "        features = mfccs.flatten()\n",
        "\n",
        "        if len(features) > fixed_length:\n",
        "            features = features[:fixed_length]\n",
        "        else:\n",
        "            features = np.pad(features, (0, fixed_length - len(features)), 'constant')\n",
        "\n",
        "        return features\n",
        "    except Exception as e:\n",
        "        st.error(f\"Error al procesar el archivo de audio: {e}\")\n",
        "        return None\n",
        "\n",
        "#--- Lógica de Carga de Modelo ---#\n",
        "\n",
        "@st.cache_resource\n",
        "def load_model_from_path(path):\n",
        "    try:\n",
        "        with open(path, 'rb') as f:\n",
        "            return joblib.load(f)\n",
        "    except FileNotFoundError:\n",
        "        return None\n",
        "\n",
        "# <<--- INICIO: BLOQUE DE CÓDIGO ACTUALIZADO Y MÁS ROBUSTO --- >>\n",
        "# Se ejecuta solo una vez para cargar el modelo por defecto.\n",
        "# Ahora incluye manejo específico para el EOFError.\n",
        "if 'model_dict' not in st.session_state:\n",
        "    default_model_path = 'pop_vs_reggaeton.pkl'\n",
        "    try:\n",
        "        with st.spinner(f\"Cargando modelo por defecto: {default_model_path}...\"):\n",
        "            model_dict = load_model_from_path(default_model_path)\n",
        "\n",
        "        if model_dict:\n",
        "            st.session_state['model_dict'] = model_dict\n",
        "            st.session_state['model_name'] = default_model_path\n",
        "        else:\n",
        "            # Maneja el caso en que el archivo no fue encontrado por la función auxiliar\n",
        "            st.session_state['model_dict'] = None\n",
        "            st.session_state['model_name'] = None\n",
        "    except EOFError:\n",
        "        # Captura el error específico que estás viendo y muestra un mensaje claro.\n",
        "        st.session_state['model_dict'] = None\n",
        "        st.session_state['model_name'] = None\n",
        "        # En la interfaz principal, se mostrará una advertencia gracias a esta lógica.\n",
        "    except Exception as e:\n",
        "        # Captura cualquier otro error inesperado durante la carga\n",
        "        st.error(f\"Ocurrió un error inesperado al cargar '{default_model_path}': {e}\")\n",
        "        st.session_state['model_dict'] = None\n",
        "        st.session_state['model_name'] = None\n",
        "# <<--- FIN: BLOQUE DE CÓDIGO ACTUALIZADO --- >>\n",
        "\n",
        "#--- Interfaz de Streamlit ---#\n",
        "st.title(\"Dashboard de Análisis Musical 🎶\")\n",
        "\n",
        "menu = [\"Inicio\", \"Cargar Modelo\", \"Detector de Género\"]\n",
        "choice = st.sidebar.selectbox(\"Menú\", menu)\n",
        "\n",
        "if choice == \"Inicio\":\n",
        "    st.header(\"Bienvenido al Dashboard de Análisis Musical\")\n",
        "    st.write(\"\"\"\n",
        "        Esta aplicación te permite predecir el género de una canción usando Machine Learning.\n",
        "    \"\"\")\n",
        "    if st.session_state.get('model_name') is None:\n",
        "         st.error(\"No se pudo cargar el modelo por defecto 'pop_vs_reggaeton.pkl'. Por favor, verifica que el archivo exista, no esté corrupto y súbelo de nuevo si es necesario.\")\n",
        "    st.info(f\"**Modelo actualmente cargado:** `{st.session_state.get('model_name', 'Ninguno')}`\")\n",
        "    st.write(\"\"\"\n",
        "        **Pasos para usar:**\n",
        "        1.  **Modelo por Defecto:** La aplicación intenta cargar `pop_vs_reggaeton.pkl`. Si falla, puedes subir uno.\n",
        "        2.  **Cargar Otro Modelo:** Ve al menú \"Cargar Modelo\" y sube tu propio archivo `.pkl`.\n",
        "        3.  **Detector de Género:** Ingresa un enlace de YouTube para obtener la predicción del modelo activo.\n",
        "    \"\"\")\n",
        "\n",
        "elif choice == \"Cargar Modelo\":\n",
        "    st.header(\"Carga de Modelo de Clasificación\")\n",
        "    st.write(\"Sube un modelo de Machine Learning en formato `.pkl` para reemplazar al modelo por defecto.\")\n",
        "\n",
        "    if st.session_state.get('model_name'):\n",
        "        st.info(f\"Modelo activo actual: **{st.session_state['model_name']}**\")\n",
        "\n",
        "    uploaded_file = st.file_uploader(\"Elige un archivo .pkl\", type=[\"pkl\"])\n",
        "\n",
        "    if uploaded_file is not None:\n",
        "        try:\n",
        "            bytes_data = uploaded_file.getvalue()\n",
        "            model_dict = joblib.load(io.BytesIO(bytes_data))\n",
        "\n",
        "            if isinstance(model_dict, dict) and 'modelo' in model_dict:\n",
        "                st.session_state['model_dict'] = model_dict\n",
        "                st.session_state['model_name'] = uploaded_file.name\n",
        "                st.success(f\"¡Modelo '{uploaded_file.name}' cargado exitosamente!\")\n",
        "                st.info(\"Este modelo está ahora activo. Ve a 'Detector de Géenero' para usarlo.\")\n",
        "            else:\n",
        "                st.error(\"El archivo .pkl no tiene el formato esperado. Debe ser un diccionario con una clave 'modelo'.\")\n",
        "\n",
        "        except Exception as e:\n",
        "            st.error(f\"Ocurrió un error al cargar el modelo: {e}\")\n",
        "\n",
        "\n",
        "elif choice == \"Detector de Género\":\n",
        "    st.header(\"Detector de Género de Canciones\")\n",
        "\n",
        "    if 'model_dict' not in st.session_state or st.session_state.get('model_dict') is None:\n",
        "        st.warning(\"No hay ningún modelo cargado. Asegúrate de que el archivo `pop_vs_reggaeton.pkl` exista y no esté corrupto, o sube un modelo manualmente desde el menú 'Cargar Modelo'.\")\n",
        "        st.stop()\n",
        "\n",
        "    model_dict = st.session_state['model_dict']\n",
        "    classifier = model_dict['modelo']\n",
        "    n_features_expected = classifier.n_features_in_\n",
        "\n",
        "    st.info(f\"Usando el modelo: **{st.session_state['model_name']}**\")\n",
        "\n",
        "    youtube_link = st.text_input(\"Ingresa el enlace de YouTube para predecir su género\")\n",
        "\n",
        "    if youtube_link:\n",
        "        if st.button(\"Predecir Género\"):\n",
        "            try:\n",
        "                with st.spinner(\"Descargando y procesando audio...\"):\n",
        "                    audio_path = download_youtube_audio(youtube_link)\n",
        "\n",
        "                    if audio_path:\n",
        "                        features = extract_features(audio_path, fixed_length=n_features_expected)\n",
        "                        os.remove(audio_path)\n",
        "\n",
        "                        if features is not None:\n",
        "                            features_reshaped = features.reshape(1, -1)\n",
        "                            prediction = classifier.predict(features_reshaped)\n",
        "                            probabilities = classifier.predict_proba(features_reshaped)\n",
        "\n",
        "                            st.write(f\"### El género predicho es: **{prediction[0]}**\")\n",
        "                            st.write(\"---\")\n",
        "                            st.write(\"#### Probabilidades por clase:\")\n",
        "\n",
        "                            for i, genre_label in enumerate(classifier.classes_):\n",
        "                                st.write(f\"- **{genre_label}:** {probabilities[0][i]*100:.2f}%\")\n",
        "\n",
        "            except Exception as e:\n",
        "                st.error(f\"Ocurrió un error inesperado durante el proceso de predicción: {e}\")"
      ],
      "metadata": {
        "id": "mtX24Js3G3SP"
      },
      "execution_count": null,
      "outputs": []
    },
    {
      "cell_type": "markdown",
      "source": [
        "## **Inicialización del Dashboard a partir de túnel local**\n",
        "\n",
        "1. **Reemplazar nombre de archivo**: Reemplaza el nombre del archivo como se indica en el comentario de la linea 6 de la celda de codigo\n",
        "\n",
        "2. **Accede al enlace provisional**: Una vez que la aplicación esté corriendo, LocalTunnel generará un enlace temporal. Haz clic o copia ese enlace para acceder a tu aplicación en el navegador (cada vez que corras la celda, el link podrá ser diferente).\n",
        "\n",
        "**Nota:**\n",
        "Para finalizar la ejecución del Dashboard ejecuta la ultima celda de codigo y sigue las instrucciones."
      ],
      "metadata": {
        "id": "VhuXzowLHDVi"
      }
    },
    {
      "cell_type": "code",
      "source": [
        "!wget https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64\n",
        "!chmod +x cloudflared-linux-amd64\n",
        "!mv cloudflared-linux-amd64 /usr/local/bin/cloudflared\n",
        "\n",
        "#Ejecutar Streamlit\n",
        "!streamlit run 0_👋_Bienvenida.py &>/content/logs.txt & #Cambiar 0_👋_Hello.py por el nombre de tu archivo principal\n",
        "\n",
        "#Exponer el puerto 8501 con Cloudflare Tunnel\n",
        "!cloudflared tunnel --url http://localhost:8501 > /content/cloudflared.log 2>&1 &\n",
        "\n",
        "#Leer la URL pública generada por Cloudflare\n",
        "import time\n",
        "time.sleep(5)  # Esperar que se genere la URL\n",
        "\n",
        "import re\n",
        "found_context = False  # Indicador para saber si estamos en la sección correcta\n",
        "\n",
        "with open('/content/cloudflared.log') as f:\n",
        "    for line in f:\n",
        "        #Detecta el inicio del contexto que nos interesa\n",
        "        if \"Your quick Tunnel has been created\" in line:\n",
        "            found_context = True\n",
        "\n",
        "        #Busca una URL si ya se encontró el contexto relevante\n",
        "        if found_context:\n",
        "            match = re.search(r'https?://\\S+', line)\n",
        "            if match:\n",
        "                url = match.group(0)  #Extrae la URL encontrada\n",
        "                print(f'Tu aplicación está disponible en: {url}')\n",
        "                break  #Termina el bucle después de encontrar la URL"
      ],
      "metadata": {
        "id": "eqKC7iozHNIG"
      },
      "execution_count": null,
      "outputs": []
    },
    {
      "cell_type": "markdown",
      "source": [
        "Finalización de ejecución del Dashboard"
      ],
      "metadata": {
        "id": "AcZJ_lPwHeUa"
      }
    },
    {
      "cell_type": "code",
      "source": [
        "import os\n",
        "\n",
        "res = input(\"Digite (1) para finalizar la ejecución del Dashboard: \")\n",
        "\n",
        "if res.upper() == \"1\":\n",
        "    os.system(\"pkill streamlit\")  # Termina el proceso de Streamlit\n",
        "    print(\"El proceso de Streamlit ha sido finalizado.\")"
      ],
      "metadata": {
        "id": "9SsCrU4gHlVU"
      },
      "execution_count": null,
      "outputs": []
    }
  ]
}